version: '3.8'
services:
    api:
        container_name: ${COMPOSE_PROJECT_NAME}-api
        build:
            context: .
            target: dev
            dockerfile: ./Dockerfile.api
        ports:
            - '${API_PORT}:${API_PORT}'
        volumes:
            # this is really just a hack:
            # We want to bind the whole project dir, cause here we are running our nest dev server and we want it to restart on file changes that we make.
            # But we don't want to also bind the node_modules, cause we have already installed them when we created the image - and want to use the ones from the image because they are specific to the image and its OS/arch/base image.
            - .:/usr/src/app
            - nodemodules:/usr/src/app/node_modules
            - ../backing-tracks-isomorphic:/usr/src/backing-tracks-isomorphic
        environment:
            API_HOST: 0.0.0.0
            REDIS_HOST: redis
            POSTGRES_HOST: pg-db
            YTDL_HOST: ytdl
        networks:
            - db
            - microservices
        depends_on:
            - pg-db
            - redis
            - ytdl

    ytdl:
        container_name: ${COMPOSE_PROJECT_NAME}-ytdl
        build:
            context: .
            target: dev
            dockerfile: ./Dockerfile.ytdl
        ports:
            - '${YTDL_PORT}:${YTDL_PORT}'
        volumes:
            - .:/usr/src/app
            - nodemodules:/usr/src/app/node_modules
            - ../backing-tracks-isomorphic:/usr/src/backing-tracks-isomorphic
        environment:
            YTDL_HOST: 0.0.0.0
            REDIS_HOST: redis
        networks:
            - microservices

    redis:
        # for prod use redis/redis-stack-server:latest which does not include redis insight
        # https://docs.bullmq.io/guide/connections
        # todo version
        image: redis/redis-stack:latest
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: unless-stopped
        ports:
            - '${REDIS_PORT}:6379'
            - '${REDIS_INSIGHT_PORT}:8001'
        environment:
            REDIS_ARGS: "--maxmemory-policy noeviction"
        volumes:
            - redis-data:/data
        networks:
            - microservices

    pg-db:
        image: postgres:16
        container_name: ${COMPOSE_PROJECT_NAME}-pg-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pg-db-data:/var/lib/postgresql/data
        networks:
            - db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s
    # pg-admin:
    #     image: dpage/pgadmin4
    #     container_name: ${COMPOSE_PROJECT_NAME}-pgadmin4_container
    #     restart: unless-stopped
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
    #         PGADMIN_DEFAULT_PASSWORD: strong-password
    #     ports:
    #         - '8888:80'
    #     volumes:
    #         - pg-admin-data:/var/lib/pgadmin
    #     depends_on:
    #         - pg-db
    #     networks:
    #         - db

volumes:
    pg-db-data:
        driver: local
    redis-data:
        driver: local
    nodemodules:
        driver: local
    # pg-admin-data:
    # driver: local
    # TODO dont use host binded volumes for the donwloands/converted

networks:
    db:
        name: ${COMPOSE_PROJECT_NAME}-db
        driver: bridge
    microservices:
        name: ${COMPOSE_PROJECT_NAME}-microservices
        driver: bridge
