version: '3.8'
services:
    api:
        container_name: ${COMPOSE_PROJECT_NAME}-api
        build:
            context: .
            target: prod
            dockerfile: ./Dockerfile.api
            args:
                - DOWNLOADED_TRACKS_PATH=${DOWNLOADED_TRACKS_PATH}
                - CONVERTED_TRACKS_PATH=${CONVERTED_TRACKS_PATH}
        command: [ "node", "dist/apps/api/main" ]
        volumes:
            - downloaded-tracks:/usr/src/app/${DOWNLOADED_TRACKS_PATH}
            - converted-tracks:/usr/src/app/${CONVERTED_TRACKS_PATH}
        ports:
            - '${API_PORT}:${API_PORT}'
        env_file:
            - .env.staging
            - .env.secret
        environment:
            API_HOST: 0.0.0.0
            POSTGRES_HOST: pg-db
            YTDL_HOST: ytdl
        networks:
            - db
            - microservices
        depends_on:
            - pg-db
            - ytdl

    ytdl:
        container_name: ${COMPOSE_PROJECT_NAME}-ytdl
        build:
            context: .
            target: prod
            dockerfile: ./Dockerfile.ytdl
            args:
                - DOWNLOADED_TRACKS_PATH=${DOWNLOADED_TRACKS_PATH}
                - CONVERTED_TRACKS_PATH=${CONVERTED_TRACKS_PATH}
        volumes:
            - downloaded-tracks:/usr/src/app/${DOWNLOADED_TRACKS_PATH}
            - converted-tracks:/usr/src/app/${CONVERTED_TRACKS_PATH}
        ports:
            - '${YTDL_PORT}:${YTDL_PORT}'
        env_file:
            - .env.staging
            - .env.secret
        environment:
            YTDL_HOST: 0.0.0.0
        networks:
            - microservices

    pg-db:
        image: postgres:16
        container_name: ${COMPOSE_PROJECT_NAME}-pg-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pg-db-data:/var/lib/postgresql/data
        networks:
            - db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s

volumes:
    downloaded-tracks:
        driver: local
    converted-tracks:
        driver: local
    pg-db-data:
        driver: local

networks:
    db:
        name: ${COMPOSE_PROJECT_NAME}-db
        driver: bridge
    microservices:
        name: ${COMPOSE_PROJECT_NAME}-microservices
        driver: bridge
